// dark-mode-react/src/Button.tsx
import { FaMoon } from "react-icons/fa";
import { LuSun } from "react-icons/lu";

interface Props {
  darkMode: boolean;
  toggleDarkMode?: () => void;
}

export const Button = ({ darkMode, toggleDarkMode }: Props) => {
  return (
    <button className="p-2 rounded-full" onClick={toggleDarkMode}>
      {darkMode ? (
        <LuSun className="text-white" size={24} />
      ) : (
        <FaMoon className="text-gray-600" size={24} />
      )}
    </button>
  );
};

// dark-mode-vue/src/components/Button.vue
<script setup lang="ts">
import 'primeicons/primeicons.css'

import { useTheme } from '@/componsables/useTheme.ts'

const { theme, toggleDarkMode } = useTheme()
</script>

<template>
  <button
    class="px-4 py-2 rounded"
    @click="toggleDarkMode"
  >
    <i :class="[
        theme ? 'pi pi-sun' : 'pi pi-moon',
        'p-2 rounded-full',  
        theme ? 'bg-white text-black' : 'bg-gray-300'
      ]"></i>
  </button>
</template>
