// dark-mode-vue/src/components/Article.vue
<script setup lang="ts">
import { articles } from '@/api'
</script>

<template>
  <div class="text-left">
    <ul>
      <li v-for="item in articles" :key="item.id">
        <h2 class="text-xl font-bold mb-2">{{ item.title }}</h2>
        <p class="mb-1 text-gray-600">{{ item.snippet }}</p>
        <span class="text-sm text-gray-500">{{ item.date.toDateString() }}</span>
      </li>
    </ul>
  </div>
</template>

// dark-mode-react/src/Article.tsx
import { articles } from "./api";

export const Article = () => {
  return (
    <div className="text-left">
      <ul>
        {articles.map((item) => (
          <li key={item.id} className="mb-6">
            <h2 className="text-xl font-bold mb-2">{item.title}</h2>
            <p className="mb-1 text-gray-600">{item.snippet}</p>
            <span className="text-sm text-gray-500">
              {item.date.toDateString()}
            </span>
          </li>
        ))}
      </ul>
    </div>
  );
};
